"""Event contract alignment guards (HD-FRP-FOUNDATION-01).

Authority chain (see ``PLATFORM_DECISION_LOG.md`` 附录 U):

    D-P10-02 / D-AUTH-22  ->  Domain Event ID = canonical UUIDv7, generated by
                              ``core.audit.interfaces.new_event_id()``; the
                              ``EventBus`` is an optional in-process auxiliary
                              and is never the delivery boundary.
    P10 schema (0013)     ->  ``DomainEvent.tenant_id`` is nullable; NULL means
                              a platform-scoped event, not an unknown tenant and
                              never a tenant-isolation bypass.

These guards run without any database or external service.
"""

from __future__ import annotations

import ast
import re
import uuid
from pathlib import Path

import pytest

from core.audit.interfaces import new_event_id
from core.event import interfaces as event_contract
from core.event.interfaces import DomainEvent

pytestmark = pytest.mark.architecture

ROOT = Path(__file__).resolve().parents[2]
EVENT_CONTRACT = ROOT / "core" / "event" / "interfaces.py"

FORBIDDEN_GENERATOR_NAMES = ("new_uuid7", "uuid_generator", "system_uuid_generator")
FORBIDDEN_PRIVILEGE_TOKENS = ("platform_admin", "bypass", "skip_authorization", "is_platform")


def _raw(path: Path = EVENT_CONTRACT) -> str:
    return path.read_text(encoding="utf-8")


def _version_of(value: str) -> int:
    return uuid.UUID(value).version


# --------------------------------------------------------------------------- #
# 1. Event identity — canonical UUIDv7, single generator, real delegation
# --------------------------------------------------------------------------- #
def test_new_event_id_is_a_canonical_uuid7() -> None:
    """The committed canonical generator produces RFC 9562 UUIDv7 values."""
    value = new_event_id()
    parsed = uuid.UUID(value)
    assert parsed.version == 7, "canonical event identity must be UUIDv7 (D-AUTH-22)"
    assert parsed.variant == uuid.RFC_4122, "UUIDv7 variant must be RFC 4122"


def test_event_module_delegates_to_the_canonical_generator(monkeypatch) -> None:
    """``core.event`` must call ``new_event_id`` — not re-implement it."""
    calls: list[bool] = []

    def _spy() -> str:
        calls.append(True)
        return "00000000-0000-7000-8000-000000000000"

    monkeypatch.setattr(event_contract, "new_event_id", _spy)
    assert event_contract._new_id() == "00000000-0000-7000-8000-000000000000"
    assert calls, "DomainEvent identity must be delegated to new_event_id()"


def test_domain_event_default_identity_is_uuid7() -> None:
    """A freshly constructed DomainEvent carries a UUIDv7 identity."""
    event = DomainEvent(type="p15.contract.alignment")
    assert _version_of(event.id) == 7


def test_event_module_has_no_second_uuid_generator_and_no_uuid4() -> None:
    """No second generator, and no legacy uuid4 leftover (D-P10-02 决策①)."""
    src = _raw()
    assert "uuid4" not in src, "uuid.uuid4() is an implementation leftover, not the contract"
    assert "import uuid" not in src, "the canonical generator lives in core.audit.interfaces"
    tree = ast.parse(src)
    defined = {
        node.name
        for node in ast.walk(tree)
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
    }
    for forbidden in FORBIDDEN_GENERATOR_NAMES:
        assert forbidden not in defined, f"second UUID generator defined: {forbidden}"
    assert "new_event_id" in src, "the canonical generator must be referenced"


# --------------------------------------------------------------------------- #
# 2. tenant_id contract — nullable, semantics distinguished
# --------------------------------------------------------------------------- #
def test_tenant_scoped_event_keeps_its_tenant() -> None:
    """``tenant_id != NULL`` = tenant-scoped event."""
    event = DomainEvent(type="p15.contract.alignment", tenant_id="tenant-x")
    assert event.tenant_id == "tenant-x"
    assert event.space_id is None, "space scope is independent and never inferred"


def test_platform_scoped_event_carries_a_null_tenant() -> None:
    """``tenant_id = NULL`` = platform-scoped event (not an unknown tenant)."""
    event = DomainEvent(type="p15.contract.alignment", tenant_id=None)
    assert event.tenant_id is None, "NULL must not be substituted by a platform tenant"


def test_platform_scope_is_not_an_authorization_bypass() -> None:
    """A NULL tenant grants nothing: no privilege field, no bypass token."""
    event = DomainEvent(type="p15.contract.alignment", tenant_id=None)
    for attribute in ("is_admin", "is_platform", "skip_authorization", "platform_admin"):
        assert not hasattr(event, attribute), f"event must not carry {attribute}"
    src = _raw()
    for token in FORBIDDEN_PRIVILEGE_TOKENS:
        assert token not in src, f"platform scope must never imply {token!r}"
    assert not re.search(r"tenant_id\s*(?:==|is)\s*None\s*and\s*.*(?:allow|admin)", src)


def test_actor_provenance_survives_platform_scope() -> None:
    """Platform scope keeps the originating actor; no system actor is invented."""
    event = DomainEvent(
        type="p15.contract.alignment", tenant_id=None, actor_id="user-1", space_id=None
    )
    assert event.actor_id == "user-1", "actor provenance is required and preserved"
    src = _raw()
    for token in ("system_subject", "service_subject", "consumer_subject", "worker_subject"):
        assert token not in src, f"no hidden platform identity: {token}"


# --------------------------------------------------------------------------- #
# 3. Documentation traceability — EventBus is not the outbox
# --------------------------------------------------------------------------- #
def test_event_bus_is_documented_as_distinct_from_the_outbox() -> None:
    """``EventBus != Outbox`` must be stated in the contract it belongs to."""
    docstring = ast.get_docstring(ast.parse(_raw())) or ""
    assert "EventBus != Outbox" in docstring, "D-P10-02 requires the distinction to be explicit"
    assert "outbox" in docstring.lower()
